const deckOfCards = [
    { id: 1, name: "card-hearts-ace", class: "card-front", isOpen: false, type: "hearts" },
    { id: 2, name: "card-hearts-king", class: "card-front", isOpen: false, type: "hearts" },
    { id: 3, name: "card-hearts-queen", class: "card-front", isOpen: false, type: "hearts" },
    { id: 4, name: "card-hearts-jack", class: "card-front", isOpen: false, type: "hearts" },
    { id: 5, name: "card-hearts-10", class: "card-front", isOpen: false, type: "hearts" },
    { id: 6, name: "card-hearts-9", class: "card-front", isOpen: false, type: "hearts" },
    { id: 7, name: "card-hearts-8", class: "card-front", isOpen: false, type: "hearts" },
    { id: 8, name: "card-hearts-7", class: "card-front", isOpen: false, type: "hearts" },
    { id: 9, name: "card-hearts-6", class: "card-front", isOpen: false, type: "hearts" },

    { id: 10, name: "card-clubs-ace", class: "card-front", isOpen: false, type: "clubs" },
    { id: 11, name: "card-clubs-king", class: "card-front", isOpen: false, type: "clubs" },
    { id: 12, name: "card-clubs-queen", class: "card-front", isOpen: false, type: "clubs" },
    { id: 13, name: "card-clubs-jack", class: "card-front", isOpen: false, type: "clubs" },
    { id: 14, name: "card-clubs-10", class: "card-front", isOpen: false, type: "clubs" },
    { id: 15, name: "card-clubs-9", class: "card-front", isOpen: false, type: "clubs" },
    { id: 16, name: "card-clubs-8", class: "card-front", isOpen: false, type: "clubs" },
    { id: 17, name: "card-clubs-7", class: "card-front", isOpen: false, type: "clubs" },
    { id: 18, name: "card-clubs-6", class: "card-front", isOpen: false, type: "clubs" },

    { id: 19, name: "card-diamonds-ace", class: "card-front", isOpen: false, type: "diamonds" },
    { id: 20, name: "card-diamonds-king", class: "card-front", isOpen: false, type: "diamonds" },
    { id: 21, name: "card-diamonds-queen", class: "card-front", isOpen: false, type: "diamonds" },
    { id: 22, name: "card-diamonds-jack", class: "card-front", isOpen: false, type: "diamonds" },
    { id: 23, name: "card-diamonds-10", class: "card-front", isOpen: false, type: "diamonds" },
    { id: 24, name: "card-diamonds-9", class: "card-front", isOpen: false, type: "diamonds" },
    { id: 25, name: "card-diamonds-8", class: "card-front", isOpen: false, type: "diamonds" },
    { id: 26, name: "card-diamonds-7", class: "card-front", isOpen: false, type: "diamonds" },
    { id: 27, name: "card-diamonds-6", class: "card-front", isOpen: false, type: "diamonds" },

    { id: 28, name: "card-spades-ace", class: "card-front", isOpen: false, type: "spades" },
    { id: 29, name: "card-spades-king", class: "card-front", isOpen: false, type: "spades" },
    { id: 30, name: "card-spades-queen", class: "card-front", isOpen: false, type: "spades" },
    { id: 31, name: "card-spades-jack", class: "card-front", isOpen: false, type: "spades" },
    { id: 32, name: "card-spades-10", class: "card-front", isOpen: false, type: "spades" },
    { id: 33, name: "card-spades-9", class: "card-front", isOpen: false, type: "spades" },
    { id: 34, name: "card-spades-8", class: "card-front", isOpen: false, type: "spades" },
    { id: 35, name: "card-spades-7", class: "card-front", isOpen: false, type: "spades" },
    { id: 36, name: "card-spades-6", class: "card-front", isOpen: false, type: "spades" },
];

export {deckOfCards}